src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $subTitle = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?string $code = null;

    #[ORM\Column]
    private ?string $amount = null;

    #[ORM\Column(type: "decimal", precision: 7, scale: 2)]
    private ?float $price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Measurement $measurement = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?ProductCategory $category = null;

    #[ORM\ManyToMany(targetEntity: Image::class, inversedBy: 'products')]
    private Collection $images;

    #[ORM\Column(length: 2000, nullable: true)]
    private ?string $ingredients = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $recommended_use = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $storage_conditions = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $main_characteristics = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSubTitle(): ?string
    {
        return $this->subTitle;
    }

    public function setSubTitle(?string $subTitle): static
    {
        $this->subTitle = $subTitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getMeasurement(): ?Measurement
    {
        return $this->measurement;
    }

    public function setMeasurement(?Measurement $measurement): static
    {
        $this->measurement = $measurement;

        return $this;
    }

    public function getCategory(): ?ProductCategory
    {
        return $this->category;
    }

    public function setCategory(?ProductCategory $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function __toString(): string
    {
        return $this->title;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        $this->images->removeElement($image);

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): void
    {
        $this->price = $price;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(?string $ingredients): static
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getRecommendedUse(): ?string
    {
        return $this->recommended_use;
    }

    public function setRecommendedUse(?string $recommended_use): static
    {
        $this->recommended_use = $recommended_use;

        return $this;
    }

    public function getStorageConditions(): ?string
    {
        return $this->storage_conditions;
    }

    public function setStorageConditions(?string $storage_conditions): static
    {
        $this->storage_conditions = $storage_conditions;

        return $this;
    }

    public function getMainCharacteristics(): ?string
    {
        return $this->main_characteristics;
    }

    public function setMainCharacteristics(?string $main_characteristics): static
    {
        $this->main_characteristics = $main_characteristics;

        return $this;
    }
}

templates/components/button.html.twig
<div class="glossy-button">
    <div class="btn"><a href="#">Заяви</a></div>
</div>

templates/components/product.html.twig
<div class="column">
    <div class="head">
        <span class="headline title">{{ product.title }}</span><br/>
        {% if product.subTitle is not empty %}
            <p>
                <span class="headline hl2 subtitle">{{ product.subTitle }}</span>
            </p>
        {% endif %}
    </div>
</div>
<div class="product-info">
    <div id="product-carousel-{{ product.id }}"
         class="product-carousel-modal carousel slide"
         data-bs-ride="carousel">
        <div class="carousel-inner product-carousel">
            {% if productImages[product.id] is defined %}
                {% for productImage in productImages[product.id] %}
                    {% if loop.index == 1 %}
                        <div class="carousel-item active">
                            <img src="/uploads/attachments/{{ productImage }}"
                                 class="d-block w-100" alt="...">
                        </div>
                    {% else %}
                        <div class="carousel-item">
                            <img src="/uploads/attachments/{{ productImage }}"
                                 class="d-block w-100" alt="...">
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <button class="carousel-control-prev" type="button"
                data-bs-target="#product-carousel-{{ product.id }}"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button"
                data-bs-target="#product-carousel-{{ product.id }}"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <p class="product-description">
        <b>{{ translations['Description']|trans }}
            : </b>{{ product.description | raw }}</p>
    <hr/>
    {% if product.ingredients is not empty %}
        <p class="product-ingredients">
            <b>{{ translations['Ingredients']|trans }}
                : </b>{{ product.ingredients | raw }}</p>
        <hr/>
    {% endif %}
    {% if product.recommendedUse is not empty %}
        <p class="product-recommended-use">
            <b>{{ translations['Recommended use']|trans }}
                : </b>{{ product.recommendedUse | raw }}</p>
        <hr/>
    {% endif %}
    {% if product.storageConditions is not empty %}
        <p class="product-storage-conditions">
            <b>{{ translations['Storage conditions']|trans }}
                : </b>{{ product.storageConditions | raw }}</p>
        <hr/>
    {% endif %}
    {% if product.mainCharacteristics is not empty %}
        <p class="product-main-characteristics">
            <b>{{ translations['Main characteristics']|trans }}
                : </b>{{ product.mainCharacteristics | raw }}</p>
        <hr/>
    {% endif %}
</div>
<div class="product-details">
    <span class="product-code">
        <i class="fa fa-barcode" style="font-size:34px"></i><br/>
        <span>{{ product.code }}</span>
        <div class="tooltiptext">Код на продукта</div>
    </span>
    <span class="product-amount">
        <i class="fa fa-balance-scale" style="font-size: 34px;" aria-hidden="true"></i><br/>
        <span>{{ product.amount }}</span>
        <span class="product-detail">{{ product.measurement.title }}</span>
        <div class="tooltiptext">Количество</div>
    </span>
    <div class="outer-circle">
        <div class="inner-circle">
            <div class="product-price">
                <i class="fa-solid fa-wallet" style="font-size: 34px;"></i><br/>
                {{ (product.price / 100) |format_currency('BGN') }}
                <div class="tooltiptext">Препоръчителна цена за потребители</div>
            </div>
        </div>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
    </div>


{#    <span class="product-price right"><b>{{ translations['PCP']|trans }}: </b><span#}
{#                class="tooltiptext">Препоръчителна цена за потребители</span><span>{{ (product.price / 100) |format_currency('BGN') }}</span></span>#}
</div>

templates/components/send_button.html.twig
<style>
    .send-btn {
        width: 150px;
        height: 50px;
        border: none;
        border-radius: 25px/50%;
        background-color: #0096ff;
        font-size: 1.5rem;
        position: relative;
        box-shadow: 0 0 0 #50c878 inset, 0 2px 5px #0095ffa6;
        transition: all 350ms ease-in-out;
        cursor: pointer;
    }

    .send-btn.checked {
        box-shadow: 200px 0 0 #50c878 inset, 0 2px 5px #50c878a6;
    }

    .circle {
        position: absolute;
        width: 100px;
        height: 100px;
        /* border: 1px solid #000; */
        border-radius: 50%;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .plane-icon {
        position: absolute;
        left: -0.5em;
        top: 50%;
        transform: translateY(-50%) rotate(-25deg);
    }

    .rotateCircle {
        animation: rotate 3s ease-in-out 1;
    }

    .hide {
        display: none;
        visibility: hidden;
    }

    @keyframes rotate {
        100% {
            transform: translate(-50%, -50%) rotate(360deg);
        }
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<button id="send-btn"
        type="submit"
        class="btn btn-lg btn-block request send-btn"
        data-sitekey="6LdX9CcpAAAAAHsbVpU56Az2rSTDJf4q7oCvys3z"
        data-action='submit'
        style="background-color: {{ currentCategory.color }};">
    <div class="circle">
        <i class="fa-solid fa-paper-plane plane-icon hide"></i>
    </div>
    Изпрати
</button>
<script>
    // let sendBtn = document.querySelector(".send-btn");
    //
    // sendBtn.addEventListener("click", () => {
    //     let planePath = sendBtn.querySelector(".circle");
    //     let planeIcon = sendBtn.querySelector(".plane-icon");
    //
    //     planePath.classList.add("rotateCircle");
    //     planeIcon.classList.remove("hide");
    //
    //     setTimeout(() => {
    //         planeIcon.classList.add("hide");
    //         planePath.classList.remove("rotateCircle");
    //     }, 2750);
    //
    //     setTimeout(() => {
    //         sendBtn.classList.add("checked");
    //         sendBtn.innerHTML = "Sent";
    //     }, 3000);
    // });
</script>